### ISSUE TITLE
terminal_print8 and terminal_measure8 removed from BearLibTerminal

### ISSUE THREAD

**Issue by denizzzka** [Elronnd/bearlibterminal-dlang#1]
isn't linkable with new  BearLibTerminal

https://bitbucket.org/cfyzium/bearlibterminal/commits/31dabc93b5b4e3d28f79a7847e4f1bc45e7af952

**Comment by moon-chilled** [comment]
Thanks for the report, I'll push a fix tomorrow.

**Comment by moon-chilled** [comment]
Fixed in 0cc4f55
